version: '3'
services:
  webapi:
    build:
      context: .
    ports:
      - "9080:8080"
    environment:
      - MongoDBSettings__ConnectionString=mongodb://mongo:password@cart-db:27017
      - CloudinarySettings__CloudName=my-cloud
      - CloudinarySettings__ApiKey=321859731299899
      - CloudinarySettings__ApiSecret=fSJ0Mfmz29oM0FclViO6D95Ysk0
    depends_on:
      - cart-db
  cart-db:
    image: mongo
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo 
      - MONGO_INITDB_ROOT_PASSWORD=password
    